server:
  port: 8090
spring:
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:file:.env[.properties]
  application:
    name: databases
  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    user: postgres
  #    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 7
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true

  upload-dir: uploads/
aws:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}